pipeline {
    agent any
    triggers{
        githubPush()
    }
    stages {
        stage('Clone Code') {
            steps {
                git 'https://github.com/shhriya/ci-cd-js-project-jenkins.git'
            }
        }

        stage('Install') {
            steps {
                bat 'npm install'
            }
        }

        stage('Test') {
            steps {
                bat 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t ci-cd-js-app .'
            }
        }

        stage('Deploy to Render') {
            steps {
                
                bat 'curl -X POST https://api.render.com/deploy/srv-cvvmdkjuibrs73bjd260?key=gJyQuR3jNtU'
            }
        }
    }
}
